### ISSUE TITLE
Upgrade to Rails 6

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1611]
# Description

Let's update our app to Rails 5! I recommend going through this [doc](https://edgeguides.rubyonrails.org/6_0_release_notes.html) on notable changes and deprecations. 

Dependant issue:
- [x] Pre upgrade benchmarking [(#1722)](#1722 )

# Tasks

- [x] Set up anenvironment for the upgrade.
- [x] Upgrade to RoR 6.
- [ ] Review application and Configurations.
  - [ ] Dev environment build
  - [ ] CircleCI build
  - [ ] Production build
- [ ] Test the upgrade with users.
- [ ] Document learnings.

# Useful Resources

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by bmwachajr** [comment]
@julianguyen I worked as part of a 2 man squad to Upgrade a previous employer's app from Rails 4 to Rails 5+. I would definitely take this one on although I am a bit guilty that I haven't completed the last issue of the project that I took on.

We shall probably have to create a project for this. A good read to get stoked is this [article from Github](https://github.blog/2018-09-28-upgrading-github-from-rails-3-2-to-5-2/)

**Comment by mapra99** [comment]
Hello! @julianguyen @bmwachajr, this is something I haven't done before, but if more hands-on it are required, I would like to be in

**Comment by julianguyen** [comment]
That would be great @mapra99! @bmwachajr, have you been able to get started? You two should definitely sync!

**Comment by bmwachajr** [comment]
Hi @mapra99, this definitely has a handful of hands-on work. And yes you can contribute. Please assign yourself to this issue.

@julianguyen I have broken down this project into 3 phases: pre-update, update, and roll-out. 

Here is the: 
- WIP project [plan](https://docs.google.com/spreadsheets/d/1rmpS5pg7agpi0rp9GSQh3zor6S78WQHH5GDwwY0caKc/edit?usp=sharing)
- Project [Board](https://github.com/ifmeorg/ifme/projects/13)

**Comment by julianguyen** [comment]
This looks great! Let me know how I can help @bmwachajr and @mapra99!

**Comment by jahvon** [comment]
Hi @bmwachajr and @mapra99. I would be interested in helping out with this!

**Comment by bmwachajr** [comment]
@jahvon sending you a message on slack

**Comment by bmwachajr** [comment]
Counterpart resource [Rails 6 Release Notes](https://guides.rubyonrails.org/6_0_release_notes.html)
