### ISSUE TITLE
Pre Rails 6 Upgrade Plan

### ISSUE THREAD

**Issue by bmwachajr** [ifmeorg/ifme#1722]
# Description

This issue benchmarks processes and documentation for the Rails 6 upgrade.
Working Doc: 
[Feature audit, Rollout plans, Rollback plans](https://docs.google.com/document/d/1e3Nugq7ep4q2MkvCgzNrnOADot11OOYa6V-O2dWgK3A/edit#)
[Perfromance metrics](https://docs.google.com/spreadsheets/d/1OFRf6MADs7Uf0DFF29UgcPpNxb-ksZ2EFtr9tPz_wk4/edit?pli=1#gid=0)

# Tasks:
- [x] Feature audit (**@bmwachajr**)
- [x] Benchmark Test coverage, Database performance and Application Performance metrics. (@jahvon )
- [x] Define Roll-back parameters (**@bmwachajr**)
- [x] Define Roll-out parameters (**@bmwachajr**)

# Useful Resources:

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by bmwachajr** [comment]
@julianguyen I completed the feature review which is a simple stock-taking of each feature.

I would like your review, [doc](https://docs.google.com/document/d/1e3Nugq7ep4q2MkvCgzNrnOADot11OOYa6V-O2dWgK3A/edit#)

PS This feature review will be useful when we do an in-person feature testing after the upgrade.

**Comment by bmwachajr** [comment]
@jahvon I am adding you tot the `Benchmark Test coverage, Database performance, and Application Performance metrics. (@mention)` task.

In future feel free to add yourself to the (**@mention**). It helps us keep track of who is handling a given to-do.

Cheers

**Comment by bmwachajr** [comment]
This issue has been completed. And we have the following guidelines.:

- [Feature audit, Rollout plans, Rollback plans](https://docs.google.com/document/d/1e3Nugq7ep4q2MkvCgzNrnOADot11OOYa6V-O2dWgK3A/edit#)

- [Ifme KPI metrics](https://docs.google.com/spreadsheets/d/1OFRf6MADs7Uf0DFF29UgcPpNxb-ksZ2EFtr9tPz_wk4/edit?pli=1#gid=0)

I believe we are ready for the upgrade.

**Comment by julianguyen** [comment]
Woot! Looks good to me. Fantastic work! :)
